[package]
name = "greengrass-sdk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.2.1"
endi = "1.1.0"
serde_json = "1.0.133"
tokio = { version = "1", features = ["rt", "sync"] }
tracing = "0.1"
uuid = "1.11.0"
